language: python

#which versions of python to test against
python:
  - "2.7"
  - "3.3"

# command to install dependencies
install:
  - pip install codecov
  - pip install coverage
#  - pip install ./lecture7/
#  - pip install -r ./lecture7/requirements.txt

script:
  - python -m unittest discover -v ./ci_play/ # command to run unit test
  - coverage run ./ci_play/test.py # command to run code coverage

#can do additional things, say send out reports, which we will discuss next tim
 after_success:
  - codecov --token=8e740575-ca2c-4017-adfb-4dcd5471c326 #upload coverage report to codecov.io
