language: python
python:
- '2.7'
- '3.3'
install:
- pip install codecov
- pip install coverage
script:
- python -m unittest discover -v ./ci_play/
- coverage run ./ci_play/test.py
after_success:
- codecov --token=8e740575-ca2c-4017-adfb-4dcd5471c326
deploy:
  provider: s3
  access_key_id: AKIAJPECOI3Z72YXP2OQ
  secret_access_key:
    secure: H9tdVT7yfc+v7lkd5JGdVuU10ibAuRYAm2i42PGnZ/eVQsNGbzbTphkzSCa0sV7qaU3Aw/krV0HZddXu8mlOBDhTH0gCE4369TOd5KaGwcfVDUKDIXGLtthCXTwzlWo8nmcup4xQo/gCh+JbJzUtWr0PEH4i47kMQ/AHkn8XOdAi7ccKWPa58TETRnSJtv33sW8VmWM7y4+4lWivA3sWSMg8gUetn013nLOLUq86udXnW4rO84GfVPLMiNKo9L3+AF8X+F/u81zuigZ0v3ZfkSrtyESxPEEBhJOiPQAUbN24m6WFuu5wu8+6ckcx8FoSQf5tm9LiH4DmM4Rk5JtNWJ70HMmUl5jWfIi+1DKs1mhcc/2RnmVDFZgu+kUUO03POTfpYJGeTFlvEEGlhZRlrJgvbrh/l9HpjmMjg5veL6YYO9YF7e9zt6+66IDadm9FqwunApxswQvZnwW9sgUyPnn0NdS22exZiN2+3+b2YXOY1zRYbtGohDjPNrCFxascj1fzHE8RQvlZmlAwGiJQJeydPPWuJ2t7vH46NCeSU28TL/0TM5Yjl66oODjQyenr+dMYRgZP64nBw7wMMtGcfAxD0dGyfs3BLjtWjTgATGIzjDzgrWltozw4T0oDUM/1z1TM3iRtfiDNvfSyU6vJMMyYPhEBM6utMt7sSyRUC6s=
  bucket: agaws
  skip_cleanup: true
  local-dir: index.html
  on:
    repo: CPS847-midterm/Assignment-1
