language: python
python:
- '2.7'
- '3.3'
install:
- pip install codecov
- pip install coverage
script:
- python -m unittest discover -v ./ci_play/
- coverage run ./ci_play/test.py
after_success:
- codecov --token=8e740575-ca2c-4017-adfb-4dcd5471c326
